/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ILucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
  const ILucideHeart: typeof import('~icons/lucide/heart')['default']
  const ISgMark: typeof import('~icons/sg/mark')['default']
}
