/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ILucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
  const ILucideCheck: typeof import('~icons/lucide/check')['default']
  const ILucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
  const ILucideChevronsDown: typeof import('~icons/lucide/chevrons-down')['default']
  const ILucideChevronsUp: typeof import('~icons/lucide/chevrons-up')['default']
  const ILucideChevronsUpDown: typeof import('~icons/lucide/chevrons-up-down')['default']
  const ILucideCircleAlert: typeof import('~icons/lucide/circle-alert')['default']
  const ILucideCircleCheckBig: typeof import('~icons/lucide/circle-check-big')['default']
  const ILucideHeart: typeof import('~icons/lucide/heart')['default']
  const ILucideInformation: typeof import('~icons/lucide/information')['default']
  const ILucideSearch: typeof import('~icons/lucide/search')['default']
  const ILucideTriangleAlert: typeof import('~icons/lucide/triangle-alert')['default']
  const ISgMark: typeof import('~icons/sg/mark')['default']
  const ISymbolArray: typeof import('~icons/symbol/array')['default']
  const ISymbolBoolean: typeof import('~icons/symbol/boolean')['default']
  const ISymbolClass: typeof import('~icons/symbol/class')['default']
  const ISymbolConstant: typeof import('~icons/symbol/constant')['default']
}
